### PR TITLE
Ingest v1.18.0

### PR DESCRIPTION
**Pull request by joeduffy**

### CODE REVIEW

**Comment by lukehoban** [comment]
Is there a `Gopkg.toml/lock` update needed here?  I assume so. Not sure if we’re planning to use @pgavlin’s new tool for generating overrides in pulumi-gcp as part of adopting there?

**Comment by joeduffy** [comment]
I don't know. Is the new process documented?

**Comment by pgavlin** [comment]
> > Is there a Gopkg.toml/lock update needed here? I assume so. Not sure if we’re planning to use @pgavlin’s new tool for generating overrides in pulumi-gcp as part of adopting there?
>
> I don't know. Is the new process documented?

Not as of yet. The tool is checked in in https://github.com/pulumi/home. I will help you get this in to `pulumi-gcp` after these changes are merged.

**Review by pgavlin — APPROVED** [review]

**Comment by joeduffy** [comment]
Thanks @pgavlin! Merging now.

**Pull request merged**
